
  const weaponFrames = {
    "Hold-Out Pistol":{
      "Power":4,
      "Damage Level":1,
      "Mode":["SS"],
      "Concealability":8,
      "Weight":.5,
      "Ammo Cap":4,
      "Ammo Load":"(c)",
      "Mounts":[],
      "FCU":"1",
      "DPV":"25",
      "Options":["Ammo Loading (break action)", "Ceramic Components", "Firing Mode (SA)", "Flechette Only", "Improved Ammo Capacity", "Improved Concealability", "Increased Power (Up to 1)", "Melee Hardening", "Metahuman Design (Troll)", "Metahuman Design (Dwarf)"]
    },
    "Light Pistol":{
      "Power":6,
      "Damage Level":1,
      "Mode":["SA"],
      "Concealability":6,
      "Weight":1.25,
      "Ammo Cap":12,
      "Ammo Load":"(c)",
      "Mounts":["Barrel","Top"],
      "FCU":1.5,
      "DPV":90,
      "Options":["Ammo Loading (no belt)", "Ceramic Components", "Firing Mode (SS, BF or SA/BF only)", "Flechette Only", "Improved Concealability", "Improved Ammo Capacity", "Improved FCU (Up to 2)", "Increased Power (Up to 1)", "Melee Hardening", "Metahuman Design (Troll)", "Metahuman Design (Dwarf)", "Weight Decrease (Up to 2)"]
    },
    "Machine Pistol":{
      "Power":6,
      "Damage Level":1,
      "Mode":["SA","BF"],
      "Concealability":6,
      "Weight":3.5,
      "Ammo Cap":30,
      "Ammo Load":"(c)",
      "Mounts":["Barrel","Top"],
      "FCU":1,
      "DPV":180,
      "Options":["Ceramic Components", "Firing Mode (FA or BF/FA only)", "Flechette Only", "Heavy Barrel", "Improved Concealability", "Improved FCU (Up to 6)", "Increased Power (Up to 1)", "Melee Hardening", "Metahuman Design (Troll)", "Metahuman Design (Dwarf)", "Recoil Compensation (Up to 1)", "Selectable Clip", "Weight Decrease (Up to 2)"]
    },
    "Heavy Pistol":{
      "Power":9,
      "Damage Level":2,
      "Mode":["SA"],
      "Concealability":5,
      "Weight":2.75,
      "Ammo Cap":10,
      "Ammo Load":"(c)",
      "Mounts":["Barrel","Top"],
      "FCU":2,
      "DPV":120,
      "Options":["Ammo Loading (break action, internal magazine and cylinder only)", "Ceramic Components", "Firing Mode (SS, BF or SA/BF only)", "Flechette Only", "Heavy Barrel", "Improved Ammo Capacity", "Improved Concealability", "Improved FCU (Up to 4)", "Increased Power (Up to 1)", "Melee Hardening", "Metahuman Design (Troll)", "Metahuman Design (Dwarf)", "Recoil Compensation 1", "Weight Decrease (Up to 6)"]
    },
    "Submachine Gun":{
      "Power":6,
      "Damage Level":2,
      "Mode":["SA","BF"],
      "Concealability":4,
      "Weight":4,
      "Ammo Cap":20,
      "Ammo Load":"(c)",
      "Mounts":["Barrel","Top","Under"],
      "FCU":1.5,
      "DPV":100,
      "Options":["Ceramic Components", "Firing Mode (BF, FA, BF/FA or SA/BF/FA only)", "Heavy Barrel", "High-Velocity Capability", "Improved Concealability", "Improved FCU (Up to 4)", "Increased Power 1", "Melee Hardening", "Metahuman Design (Troll)", "Metahuman Design (Dwarf)", "Recoil Compensation (Up to 2)", "Selectable Clip", "Weight Decrease (Up to 8)"]
    },
    "Shotgun":{
      "Power":8,
      "Damage Level":3,
      "Mode":["SA"],
      "Concealability":3,
      "Weight":4.5,
      "Ammo Cap":5,
      "Ammo Load":"(m)",
      "Mounts":["Barrel","Top","Under"],
      "FCU":2.5,
      "DPV":130,
      "Options":["Ammo Loading (break action or clip only)", "Barrel Extension", "Barrel Reduction", "Bullpup Configuration", "Ceramic Components", "Firing Mode (SS, BF or SA/BF only)", "Heavy Barrel", "Improved Ammo Capacity", "Improved Concealability", "Improved FCU (Up to 4)", "Increased Power (Up to 2)", "Melee Hardening", "Metahuman Design (Troll)", "Metahuman Design (Dwarf)", "Recoil Compensation (Up to 1)", "Selectable Clip", "Weight Decrease (Up to 6)"]
    },
    "Taser":{
      "Power":10,
      "Damage Level":7,
      "Mode":["SA"],
      "Concealability":5,
      "Weight":2.5,
      "Ammo Cap":3,
      "Ammo Load":"(m)",
      "Mounts":["Top"],
      "FCU":1,
      "DPV":200,
      "Options":["Ceramic Components", "Improved Concealability", "Increased Power (Up to 2)", "Melee Hardening", "Metahuman Design (Troll)", "Metahuman Design (Dwarf)", "Weight Decrease (Up to 2)"]
    },
    "Sport Rifle":{
      "Power":7,
      "Damage Level":3,
      "Mode":["SA"],
      "Concealability":2,
      "Weight":4.5,
      "Ammo Cap":5,
      "Ammo Load":"(m)",
      "Mounts":["Barrel","Top","Under"],
      "FCU":2.5,
      "DPV":125,
      "Options":["Ammo Loading (clip only)", "Barrel Extension", "Barrel Reduction", "Bullpup Configuration", "Ceramic Components", "Easy Breakdown", "Firing Mode (SS or SA/BF only)", "Heavy Barrel", "Improved Ammo Capacity", "Improved Concealability", "Improved FCU (up to 4)", "Increased Power (Up to 2)", "Melee Hardening", "Metahuman Design (Troll)", "Metahuman Design (Dwarf)", "Recoil Compensation 1", "Selectable Clip", "Weight Decrease (Up to 6)"]
    },
    "Assault Rifle":{
      "Power":8,
      "Damage Level":2,
      "Mode":["SA","BF","FA"],
      "Concealability":3,
      "Weight":3,
      "Ammo Cap":6,
      "Ammo Load":"(c)",
      "Mounts":["Barrel","Top","Under"],
      "FCU":3,
      "DPV":225,
      "Options":["Barrel Extension", "Barrel Reduction", "Bullpup Configuration", "Ceramic Components", "Easy Breakdown","Heavy Barrel", "High-Velocity Capability", "Improved Concealability", "Improved FCU 1", "Increased Power 1", "Melee Hardening", "Metahuman Design (Troll)", "Metahuman Design (Dwarf)", "Recoil Compensation (up to 2)", "Selectable Clip", "Weight Decrease (Up to 8)"]
    },
    "Sniper Rifle":{
      "Power":14,
      "Damage Level":3,
      "Mode":["SA"],
      "Concealability":0,
      "Weight":6,
      "Ammo Cap":6,
      "Ammo Load":"(m)",
      "Mounts":["Barrel","Top","Under"],
      "FCU":2.5,
      "DPV":800,
      "Options":["Ammo Loading (clip only)", "Barrel Extension", "Barrel Reduction", "Ceramic Components", "Easy Breakdown", "Firing Mode (SS only)", "Heavy Barrel", "Improved Ammo Capacity", "Improved FCU (Up to 4)", "Increased Power (Up to 2)", "Metahuman Design (Troll)", "Metahuman Design (Dwarf)", "Recoil Compensation (Up to 1)", "Selectable Clip", "Weight Decrease (Up to 6)"]
    },
    "Light Machine Gun":{
      "Power":7,
      "Damage Level":3,
      "Mode":["BF","FA"],
      "Concealability":0,
      "Weight":12,
      "Ammo Cap":40,
      "Ammo Load":"(c)",
      "Mounts":["Barrel","Top","Under"],
      "FCU":4,
      "DPV":425,
      "Options":["Ammo Loading (belt)", "Firing Mode (SA, BF, FA, SA/BF or SA/BF/FA only)", "Heavy Barrel", "High-Velocity Capability", "Increased Power (Up to 1)", "Metahuman Design (Troll)", "Metahuman Design (Dwarf)", "Recoil Compensation (Up to 2)", "Selectable Clip", "Weight Decrease (Up to 12)"]
    },
    "Medium Machine Gun":{
      "Power":9,
      "Damage Level":3,
      "Mode":["FA"],
      "Concealability":0,
      "Weight":15,
      "Ammo Cap":30,
      "Ammo Load":"(c)",
      "Mounts":["Barrel","Top","Under"],
      "FCU":4,
      "DPV":700,
      "Options":["Ammo Loading (belt only)", "Heavy Barrel", "High-Velocity Capability", "Increased Power (Up to 1)", "Metahuman Design (Troll)", "Metahuman Design (Dwarf)", "Recoil Compensation (Up to 2)", "Selectable Clip", "Weight Decrease (Up to 16)"]
    },
    "Heavy Machine Gun":{
      "Power":10,
      "Damage Level":3,
      "Mode":["FA"],
      "Concealability":0,
      "Weight":18,
      "Ammo Cap":30,
      "Ammo Load":"(c)",
      "Mounts":["Barrel","Top","Under"],
      "FCU":4,
      "DPV":1000,
      "Options":["Ammo Loading (belt only)", "Heavy Barrel", "High-Velocity Capability", "Increased Power (Up to 1)", "Metahuman Design (Troll)", "Metahuman Design (Dwarf)", "Recoil Compensation (Up to 2)", "Selectable Clip", "Weight Decrease (Up to 16)"]
    },
    "Assault Cannon":{
      "Power":18,
      "Damage Level":4,
      "Mode":["SS"],
      "Concealability":0,
      "Weight":22,
      "Ammo Cap":20,
      "Ammo Load":"(c)",
      "Mounts":["Barrel","Top","Under"],
      "FCU":4,
      "DPV":1400,
      "Options":["Ammo Loading (belt only)", "Heavy Barrel", "Increased Power (Up to 2)", "Metahuman Design (Troll)", "Metahuman Design (Dwarf)", "Recoil Compensation (Up to 1)", "Weight Decrease (Up to 12)"]
    }
  }
export default weaponFrames;