const Modifications = {
    "Custom Finish":{
        "Name":"Custom Finish",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"None",
        "Tools":"Kit/Shop",
        "Weight":0,
        "FCU":0,
        "DP":20,
        "IncompatiableWith":[]
    },
    "Embossing/Engraving":{
        "Name":"Embossing/Engraving",
        "Skill":"(Weapon) B/R",
        "InstallTime":"14 Hours",
        "InstallTN":4,
        "Mount":"None",
        "Tools":"Kit",
        "Weight":0,
        "FCU":0,
        "DP":20,
        "IncompatiableWith":[]
    },
    "Gas Vent II":{
        "Name":"Gas Vent II",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":5,
        "Mount":"Barrel",
        "Tools":"Shop",
        "Weight":.5,
        "FCU":-.5,
        "DP":90,
        "RC":2,
        "IncompatiableWith":["Gas Vent IV","Gas Vent III"]
    },
    "Gas Vent III":{
        "Name":"Gas Vent III",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":5,
        "Mount":"Barrel",
        "Tools":"Shop",
        "Weight":.75,
        "FCU":-.75,
        "DP":140,
        "RC":3,
        "IncompatiableWith":["Gas Vent IV","Gas Vent II"],
    },
    "Gas Vent IV":{
        "Name":"Gas Vent IV",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":5,
        "Mount":"Barrel",
        "Tools":"Shop",
        "Weight":.75,
        "FCU":-1,
        "DP":200,
        "RC":4,
        "IncompatiableWith":["Gas Vent III","Gas Vent II"],
    },
    "Safe Target System":{
        "Name":"Safe Target System",
        "Skill":"Electronics B/R, (Weapon) B/R",
        "InstallTime":"18 Hours",
        "InstallTN":5,
        "Mount":"None",
        "Tools":"Shop",
        "Weight":1,
        "FCU":-.25,
        "DP":40,
        "IncompatiableWith":[],
    },
    "Smartgun System (Internal)":{
        "Name":"Smartgun System (Internal)",
        "Skill":"Electronics B/R, (Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":5,
        "Mount":"None",
        "Tools":"Shop",
        "Weight":.5,
        "FCU":-.5,
        "DP":"frame base DPV",
        "IncompatiableWith":[],
    },
    "Smartgun System 2 (Internal) - Hold-Out Pistol":{
        "Name":"Smartgun System 2 (Internal)",
        "Skill":"Electronics B/R, (Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":5,
        "Mount":"None",
        "Tools":"Shop",
        "Weight":.5,
        "FCU":-.5,
        "DP":"38",
        "IncompatiableWith":[],
    },
    "Smartgun System 2 (Internal) - Light Pistol":{
        "Name":"Smartgun System 2 (Internal)",
        "Skill":"Electronics B/R, (Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":5,
        "Mount":"None",
        "Tools":"Shop",
        "Weight":.5,
        "FCU":-.5,
        "DP":"135",
        "IncompatiableWith":[],
    },
    "Smartgun System 2 (Internal) - Machine Pistol":{
        "Name":"Smartgun System 2 (Internal)",
        "Skill":"Electronics B/R, (Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":5,
        "Mount":"None",
        "Tools":"Shop",
        "Weight":.5,
        "FCU":-.5,
        "DP":"270",
        "IncompatiableWith":[],
    },
    "Smartgun System 2 (Internal) - Heavy Pistol":{
        "Name":"Smartgun System 2 (Internal)",
        "Skill":"Electronics B/R, (Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":5,
        "Mount":"None",
        "Tools":"Shop",
        "Weight":.5,
        "FCU":-.5,
        "DP":"180",
        "IncompatiableWith":[]
    },
    "Smartgun System 2 (Internal) - Submachine Gun":{
        "Name":"Smartgun System 2 (Internal)",
        "Skill":"Electronics B/R, (Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":5,
        "Mount":"None",
        "Tools":"Shop",
        "Weight":.5,
        "FCU":-.5,
        "DP":"150",
        "IncompatiableWith":[]
    },
    "Smartgun System 2 (Internal) - Shotgun":{
        "Name":"Smartgun System 2 (Internal)",
        "Skill":"Electronics B/R, (Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":5,
        "Mount":"None",
        "Tools":"Shop",
        "Weight":.5,
        "FCU":-.5,
        "DP":"195",
        "IncompatiableWith":[]
    },
    "Smartgun System 2 (Internal) - Taser":{
        "Name":"Smartgun System 2 (Internal)",
        "Skill":"Electronics B/R, (Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":5,
        "Mount":"None",
        "Tools":"Shop",
        "Weight":.5,
        "FCU":-.5,
        "DP":"300",
        "IncompatiableWith":[]
    },
    "Smartgun System 2 (Internal) - Sport Rifle":{
        "Name":"Smartgun System 2 (Internal)",
        "Skill":"Electronics B/R, (Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":5,
        "Mount":"None",
        "Tools":"Shop",
        "Weight":.5,
        "FCU":-.5,
        "DP":"188",
        "IncompatiableWith":[]
    },
    "Smartgun System 2 (Internal) - Assault Rifle":{
        "Name":"Smartgun System 2 (Internal)",
        "Skill":"Electronics B/R, (Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":5,
        "Mount":"None",
        "Tools":"Shop",
        "Weight":.5,
        "FCU":-.5,
        "DP":"338",
        "IncompatiableWith":[]
    },
    "Smartgun System 2 (Internal) - Sniper Rifle":{
        "Name":"Smartgun System 2 (Internal)",
        "Skill":"Electronics B/R, (Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":5,
        "Mount":"None",
        "Tools":"Shop",
        "Weight":.5,
        "FCU":-.5,
        "DP":"1200",
        "IncompatiableWith":[]
    },
    "Smartgun System 2 (Internal) - Light Machine Gun":{
        "Name":"Smartgun System 2 (Internal)",
        "Skill":"Electronics B/R, (Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":5,
        "Mount":"None",
        "Tools":"Shop",
        "Weight":.5,
        "FCU":-.5,
        "DP":"638",
        "IncompatiableWith":[]
    },
    "Smartgun System 2 (Internal) - Medium Machine Gun":{
        "Name":"Smartgun System 2 (Internal)",
        "Skill":"Electronics B/R, (Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":5,
        "Mount":"None",
        "Tools":"Shop",
        "Weight":.5,
        "FCU":-.5,
        "DP":"1050",
        "IncompatiableWith":[]
    },
    "Smartgun System 2 (Internal) - Heavy Machine Gun":{
        "Name":"Smartgun System 2 (Internal)",
        "Skill":"Electronics B/R, (Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":5,
        "Mount":"None",
        "Tools":"Shop",
        "Weight":.5,
        "FCU":-.5,
        "DP":"1500",
        "IncompatiableWith":[]
    },
    "Smartgun System 2 (Internal) - Assault Cannon":{
        "Name":"Smartgun System 2 (Internal)",
        "Skill":"Electronics B/R, (Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":5,
        "Mount":"None",
        "Tools":"Shop",
        "Weight":.5,
        "FCU":-.5,
        "DP":"2100",
        "IncompatiableWith":[]
    },
    "Smartgun System (External)":{
        "Name": "Smartgun System (External)",
        "Skill":"Electronics B/R",
        "InstallTime":"2 Hours",
        "InstallTN":4,
        "Mount":"Top,Under",
        "Tools":"Kit",
        "Weight":.5,
        "FCU":-.25,
        "DP":120,
        "IncompatiableWith":[]
    },
    "Smartgun System 2 (External)":{
        "Name": "Smartgun System 2 (External)",
        "Skill":"Electronics B/R",
        "InstallTime":"2 Hours",
        "InstallTN":4,
        "Mount":"Top,Under",
        "Tools":"Kit",
        "Weight":.5,
        "FCU":-.25,
        "DP":160,
        "IncompatiableWith":[]
    },
    "Voice Activation":{
        "Name":"Voice Activation",
        "Skill":"Electronics B/R",
        "InstallTime":"24 Hours",
        "InstallTN":6,
        "Mount":"None",
        "Tools":"Shop",
        "Weight":.1,
        "FCU":-.25,
        "DP":50,
        "IncompatiableWith":[]
    },
    "Biometric Safety":{
        "Name":"Biometric Safety",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":6,
        "Mount":"None",
        "Tools":"Shop",
        "Weight":.1,
        "FCU":-.25,
        "DP":450,
        "IncompatiableWith":[]
    },
    "Bipod":{
        "Name":"Bipod",
        "Skill":"(Weapon) B/R",
        "InstallTime":"8 Hours",
        "InstallTN":3,
        "Mount":"Under",
        "Tools":"kit",
        "Weight":2,
        "FCU":0,
        "DP":80,
        "IncompatiableWith":[]
    },
    "Extended Clip":{
        "Name":"Extended Clip",
        "Skill":"(Weapon) B/R",
        "InstallTime":"8 Hours",
        "InstallTN":3,
        "Mount":"None",
        "Tools":"Shop",
        "Weight":2,
        "FCU":0,
        "DP":2,
        "Extra":"+1 Round Added",
        "IncompatiableWith":[]
    },
    "Foregrip":{
        "Name":"Foregrip",
        "Skill":"(Weapon) B/R",
        "InstallTime":"36 Hours",
        "InstallTN":3,
        "Mount":"Under",
        "Tools":"Kit",
        "Weight":.5,
        "FCU":0,
        "DP":50,
        "RC":1,
        "IncompatiableWith":[]
    },
    "Full Auto":{
        "Name":"Foregrip",
        "Skill":"(Weapon) B/R",
        "InstallTime":"72 Hours",
        "InstallTN":9,
        "Mount":"None",
        "Tools":"Kit",
        "Weight":.5,
        "FCU":-1,
        "DP":120,
        "RC":-1,
        "IncompatiableWith":[]
    },
    "Laser Sight (Low-power)":{
        "Name":"Laser Sight (Low-power)",
        "Skill":"Electronics B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"Top,Under",
        "Tools":"Kit",
        "Weight":.25,
        "FCU":-.25,
        "DP":100,
        "IncompatiableWith":[]
    },
    "Laser Sight (High-power)":{
        "Name":"Laser Sight (High-power)",
        "Skill":"Electronics B/R",
        "InstallTime":"48 Hours",
        "InstallTN":4,
        "Mount":"Top,Under",
        "Tools":"Kit",
        "Weight":.25,
        "FCU":-.25,
        "DP":280,
        "IncompatiableWith":[]
    },
    "Laser Target Designator":{
        "Name":"Laser Target Designator",
        "Skill":"Electronics B/R",
        "InstallTime":"48 Hours",
        "InstallTN":4,
        "Mount":"Top,Under",
        "Tools":"Kit",
        "Weight":.5,
        "FCU":-.25,
        "DP":740,
        "IncompatiableWith":[]
    },
    "Personalized Grip":{
        "Name":"Personalized Grip",
        "Skill":"Electronics B/R",
        "InstallTime":"24 Hours",
        "InstallTN":5,
        "Mount":"None",
        "Tools":"Kit",
        "Weight":0,
        "FCU":0,
        "DP":25,
        "RC":1,
        "IncompatiableWith":[]
    },
    "Range Finder":{
        "Name":"Range Finder",
        "Skill":"Electronics B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"Top,Under",
        "Tools":"Kit",
        "Weight":.1,
        "FCU":-.25,
        "DP":30,
        "IncompatiableWith":[]
    },
    "Underbarrel Weight":{
        "Name":"Underbarrel Weight",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"Under",
        "Tools":"Kit",
        "Weight":1,
        "FCU":-.25,
        "DP":25,
        "RC":1,
        "IncompatiableWith":[]
    },
    "Remove Safety":{
        "Name":"Remove Safety",
        "Skill":"(Weapon) B/R",
        "InstallTime":"18 Hours",
        "InstallTN":5,
        "Mount":"None",
        "Tools":"Kit",
        "Weight":0,
        "FCU":0,
        "DP":30,
        "IncompatiableWith":[]
    },
    "Remove Trigger":{
        "Name":"Remove Trigger",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":5,
        "Mount":"None",
        "Tools":"Shop",
        "Weight":0,
        "FCU":-.5,
        "DP":50,
        "Extra":"Must have Smartlink to Fire",
        "IncompatiableWith":[]
    },
    "Tripod":{
        "Name":"Tripod",
        "Skill":"(Weapon) B/R",
        "InstallTime":"12 Hours",
        "InstallTN":3,
        "Mount":"Under",
        "Tools":"Kit",
        "Weight":8,
        "FCU":0,
        "DP":120,
        "IncompatiableWith":[]
    },
    "Sound Suppressor":{
        "Name":"Sound Suppressor",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"Barrel",
        "Tools":"Kit",
        "Weight":.5,
        "FCU":-.25,
        "DP":150,
        "IncompatiableWith":[]
    },
    "Ultrasound Sight":{
        "Name":"Ultrasound Sight",
        "Skill":"Electronics B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"Top,Under",
        "Tools":"Kit",
        "Weight":.25,
        "FCU":-.25,
        "DP":260,
        "IncompatiableWith":[]
    },
    "Silencer":{
        "Name":"Silencer",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"Barrel",
        "Tools":"Kit",
        "Weight":.2,
        "FCU":-.25,
        "DP":100,
        "IncompatiableWith":[]
    },
    "Rigid Stocks":{
        "Name":"Rigid Stocks",
        "Skill":"(Weapon) B/R",
        "InstallTime":"36 Hours",
        "InstallTN":4,
        "Mount":"None",
        "Tools":"Kit",
        "Weight":.5,
        "FCU":0,
        "DP":40,
        "RC":1,
        "Concealability":-1,
        "IncompatiableWith":[]
    },
    "Folding Stock":{
        "Name":"Folding Stock",
        "Skill":"(Weapon) B/R",
        "InstallTime":"36 Hours",
        "InstallTN":4,
        "Mount":"None",
        "Tools":"Kit",
        "Weight":.5,
        "FCU":0,
        "DP":40,
        "RC":1,
        "IncompatiableWith":[]
    },
    "Shock Pads":{
        "Name":"Folding Stock",
        "Skill":"(Weapon) B/R",
        "InstallTime":"2 Hours",
        "InstallTN":3,
        "Mount":"None",
        "Tools":"Kit",
        "Weight":2.5,
        "FCU":0,
        "DP":40,
        "RC":1,
        "IncompatiableWith":[]
    },
    "Hip Pads":{
        "Name":"Folding Stock",
        "Skill":"(Weapon) B/R",
        "InstallTime":"2 Hours",
        "InstallTN":3,
        "Mount":"None",
        "Tools":"Kit",
        "Weight":2,
        "FCU":0,
        "DP":40,
        "RC":1,
        "IncompatiableWith":[]
    },
    "Sawed-Off Shotgun Barrel (Kit Installed)":{
        "Name":"Sawed-Off Shotgun Barrel (Kit Installed)",
        "Skill":"Shotguns B/R",
        "InstallTime":"2 Hours",
        "InstallTN":3,
        "Mount":"Barrel",
        "Tools":"Kit",
        "Weight":-1,
        "FCU":0,
        "DP":8,
        "Concealability":2,
        "Extra":"+1 TN on all shots",
        "IncompatiableWith":["Sawed-Off Shotgun Barrel (Shop Installed)", "Barrel Extension", "Barrel Reduction"] 
    },
    "Sawed-Off Shotgun Barrel (Shop Installed)":{
        "Name":"Sawed-Off Shotgun Barrel (Shop Installed)",
        "Skill":"Shotguns B/R",
        "InstallTime":"2 Hours",
        "InstallTN":3,
        "Mount":"Barrel",
        "Tools":"Shop",
        "Weight":-1,
        "FCU":0,
        "DP":8,
        "Concealability":2,
        "IncompatiableWith":["Sawed-Off Shotgun Barrel (Kit Installed)", "Barrel Extension", "Barrel Reduction" ]
    },
    "Imaging Systems (Flashlight)":{
        "Name":"Imaging Systems (Flashlight)",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"Top,Under",
        "Tools":"Kit",
        "Weight":.25,
        "FCU":-.25,
        "DP":25,
        "IncompatiableWith":[]
    },
    "Imaging Systems (Gun Cam)":{
        "Name":"Imaging Systems (Gun Cam)",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"Top,Under",
        "Tools":"Kit",
        "Weight":.25,
        "FCU":-.25,
        "DP":400,
        "IncompatiableWith":[]
    },
    "Imaging Systems (Low-light)":{
        "Name":"Imaging Systems (Low-light)",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"Top,Under",
        "Tools":"Kit",
        "Weight":.25,
        "FCU":-.25,
        "DP":300,
        "IncompatiableWith":[]
    },
    "Imaging Systems (Magnification 1)":{
        "Name":"Imaging Systems (Magnification 1)",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"Top,Under",
        "Tools":"Kit",
        "Weight":.25,
        "FCU":-.25,
        "DP":100,
        "IncompatiableWith":[]
    },
    "Imaging Systems (Magnification 2)":{
        "Name":"Imaging Systems (Magnification 2)",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"Top,Under",
        "Tools":"Kit",
        "Weight":.25,
        "FCU":-.25,
        "DP":160,
        "IncompatiableWith":[]
    },
    "Imaging Systems (Magnification 3)":{
        "Name":"Imaging Systems (Magnification 3)",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"Top,Under",
        "Tools":"Kit",
        "Weight":.25,
        "FCU":-.25,
        "DP":240,
        "IncompatiableWith":[]
    },
    "Imaging Systems (Thermographic)":{
        "Name":"Imaging Systems (Thermographic)",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"Top,Under",
        "Tools":"Kit",
        "Weight":.25,
        "FCU":-.25,
        "DP":300,
        "IncompatiableWith":[]
    },
    "Underbarrel Weapon (Bayonet)":{
        "Name":"Underbarrel Weapon (Bayonet)",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"Under",
        "Tools":"Kit",
        "Weight":.75,
        "FCU":-.25,
        "DP":10,
        "IncompatiableWith":["Underbarrel Weapon (Flamethrower)", "Underbarrel Weapon (Grenade Launcher)","Underbarrel Weapon (Gapple Gun)"]
    },
    "Underbarrel Weapon (Gapple Gun)":{
        "Name":"Underbarrel Weapon (Gapple Gun)",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"Under",
        "Tools":"Kit",
        "Weight":2,
        "FCU":-.25,
        "DP":100,
        "IncompatiableWith":["Underbarrel Weapon (Flamethrower)", "Underbarrel Weapon (Grenade Launcher)","Underbarrel Weapon (Bayonet)"]
    },
    "Underbarrel Weapon (Grenade Launcher)":{
        "Name":"Underbarrel Weapon (Grenade Launcher)",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"Under",
        "Tools":"Kit",
        "Weight":2,
        "FCU":-.25,
        "DP":360,
        "IncompatiableWith":["Underbarrel Weapon (Flamethrower)", "Underbarrel Weapon (Gapple Gun)","Underbarrel Weapon (Bayonet)"]
    },
    "Underbarrel Weapon (Flamethrower)":{
        "Name":"Underbarrel Weapon (Flamethrower)",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"Under",
        "Tools":"Kit",
        "Weight":0,
        "FCU":-.25,
        "DP":240,
        "IncompatiableWith":["Underbarrel Weapon (Grenade Launcher)", "Underbarrel Weapon (Gapple Gun)","Underbarrel Weapon (Bayonet)"]
    }
}
export default Modifications;