const Modifications = {
    "Custom Finish":{
        "Name":"Custom Finish",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"None",
        "Tools":"Kit/Shop",
        "Weight":0,
        "FCU":0,
        "DP":20
    },
    "Embossing/Engraving":{
        "Name":"Embossing/Engraving",
        "Skill":"(Weapon) B/R",
        "InstallTime":"14 Hours",
        "InstallTN":4,
        "Mount":"None",
        "Tools":"Kit",
        "Weight":0,
        "FCU":0,
        "DP":20
    },
    "Gas Vent II":{
        "Name":"Gas Vent II",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":5,
        "Mount":"Barrel",
        "Tools":"Shop",
        "Weight":.5,
        "FCU":-.5,
        "DP":90,
        "RC":2
    },
    "Gas Vent III":{
        "Name":"Gas Vent III",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":5,
        "Mount":"Barrel",
        "Tools":"Shop",
        "Weight":.75,
        "FCU":-.75,
        "DP":140,
        "RC":3
    },
    "Gas Vent IV":{
        "Name":"Gas Vent IV",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":5,
        "Mount":"Barrel",
        "Tools":"Shop",
        "Weight":.75,
        "FCU":-1,
        "DP":200,
        "RC":4
    },
    "Safe Target System":{
        "Name":"Safe Target System",
        "Skill":"Electronics B/R, (Weapon) B/R",
        "InstallTime":"18 Hours",
        "InstallTN":5,
        "Mount":"None",
        "Tools":"Shop",
        "Weight":1,
        "FCU":-.25,
        "DP":40,
    },
    "Smartgun System (Internal)":{
        "Name":"Smartgun System (Internal)",
        "Skill":"Electronics B/R, (Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":5,
        "Mount":"None",
        "Tools":"Shop",
        "Weight":.5,
        "FCU":-.5,
        "DP":"frame base DPV"
    },
    "Smartgun System 2 (Internal)":{
        "Name":"Smartgun System 2 (Internal)",
        "Skill":"Electronics B/R, (Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":5,
        "Mount":"None",
        "Tools":"Shop",
        "Weight":.5,
        "FCU":-.5,
        "DP":"frame base DPV x 1.5"
    },
    "Smartgun System (External)":{
        "Name": "Smartgun System (External)",
        "Skill":"Electronics B/R",
        "InstallTime":"2 Hours",
        "InstallTN":4,
        "Mount":"Top,Under",
        "Tools":"Kit",
        "Weight":.5,
        "FCU":-.25,
        "DP":120
    },
    "Smartgun System 2 (External)":{
        "Name": "Smartgun System 2 (External)",
        "Skill":"Electronics B/R",
        "InstallTime":"2 Hours",
        "InstallTN":4,
        "Mount":"Top,Under",
        "Tools":"Kit",
        "Weight":.5,
        "FCU":-.25,
        "DP":160
    },
    "Voice Activation":{
        "Name":"Voice Activation",
        "Skill":"Electronics B/R",
        "InstallTime":"24 Hours",
        "InstallTN":6,
        "Mount":"None",
        "Tools":"Shop",
        "Weight":.1,
        "FCU":-.25,
        "DP":50
    },
    "Biometric Safety":{
        "Name":"Biometric Safety",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":6,
        "Mount":"None",
        "Tools":"Shop",
        "Weight":.1,
        "FCU":-.25,
        "DP":450
    },
    "Bipod":{
        "Name":"Bipod",
        "Skill":"(Weapon) B/R",
        "InstallTime":"8 Hours",
        "InstallTN":3,
        "Mount":"Under",
        "Tools":"kit",
        "Weight":2,
        "FCU":0,
        "DP":80
    },
    "Extended Clip":{
        "Name":"Extended Clip",
        "Skill":"(Weapon) B/R",
        "InstallTime":"8 Hours",
        "InstallTN":3,
        "Mount":"None",
        "Tools":"Shop",
        "Weight":2,
        "FCU":0,
        "DP":2,
        "Extra":"+1 Round Added"
    },
    "Foregrip":{
        "Name":"Foregrip",
        "Skill":"(Weapon) B/R",
        "InstallTime":"36 Hours",
        "InstallTN":3,
        "Mount":"Under",
        "Tools":"Kit",
        "Weight":.5,
        "FCU":0,
        "DP":50,
        "RC":1
    },
    "Full Auto":{
        "Name":"Foregrip",
        "Skill":"(Weapon) B/R",
        "InstallTime":"72 Hours",
        "InstallTN":9,
        "Mount":"None",
        "Tools":"Kit",
        "Weight":.5,
        "FCU":-1,
        "DP":120,
        "RC":-1
    },
    "Laser Sight (Low-power)":{
        "Name":"Laser Sight (Low-power)",
        "Skill":"Electronics B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"Top,Under",
        "Tools":"Kit",
        "Weight":.25,
        "FCU":-.25,
        "DP":100
    },
    "Laser Sight (High-power)":{
        "Name":"Laser Sight (High-power)",
        "Skill":"Electronics B/R",
        "InstallTime":"48 Hours",
        "InstallTN":4,
        "Mount":"Top,Under",
        "Tools":"Kit",
        "Weight":.25,
        "FCU":-.25,
        "DP":280
    },
    "Laser Target Designator":{
        "Name":"Laser Target Designator",
        "Skill":"Electronics B/R",
        "InstallTime":"48 Hours",
        "InstallTN":4,
        "Mount":"Top,Under",
        "Tools":"Kit",
        "Weight":.5,
        "FCU":-.25,
        "DP":740
    },
    "Personalized Grip":{
        "Name":"Personalized Grip",
        "Skill":"Electronics B/R",
        "InstallTime":"24 Hours",
        "InstallTN":5,
        "Mount":"None",
        "Tools":"Kit",
        "Weight":0,
        "FCU":0,
        "DP":25,
        "RC":1
    },
    "Range Finder":{
        "Name":"Range Finder",
        "Skill":"Electronics B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"Top,Under",
        "Tools":"Kit",
        "Weight":.1,
        "FCU":-.25,
        "DP":30
    },
    "Underbarrel Weight":{
        "Name":"Underbarrel Weight",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"Under",
        "Tools":"Kit",
        "Weight":1,
        "FCU":-.25,
        "DP":25,
        "RC":1
    },
    "Remove Safety":{
        "Name":"Remove Safety",
        "Skill":"(Weapon) B/R",
        "InstallTime":"18 Hours",
        "InstallTN":5,
        "Mount":"None",
        "Tools":"Kit",
        "Weight":0,
        "FCU":0,
        "DP":30
    },
    "Remove Trigger":{
        "Name":"Remove Trigger",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":5,
        "Mount":"None",
        "Tools":"Shop",
        "Weight":0,
        "FCU":-.5,
        "DP":50,
        "Extra":"Must have Smartlink to Fire"
    },
    "Tripod":{
        "Name":"Tripod",
        "Skill":"(Weapon) B/R",
        "InstallTime":"12 Hours",
        "InstallTN":3,
        "Mount":"Under",
        "Tools":"Kit",
        "Weight":8,
        "FCU":0,
        "DP":120
    },
    "Sound Suppressor":{
        "Name":"Sound Suppressor",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"Barrel",
        "Tools":"Kit",
        "Weight":.5,
        "FCU":-.25,
        "DP":150
    },
    "Ultrasound Sight":{
        "Name":"Ultrasound Sight",
        "Skill":"Electronics B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"Top,Under",
        "Tools":"Kit",
        "Weight":.25,
        "FCU":-.25,
        "DP":260
    },
    "Silencer":{
        "Name":"Silencer",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"Barrel",
        "Tools":"Kit",
        "Weight":.2,
        "FCU":-.25,
        "DP":100
    },
    "Rigid Stocks":{
        "Name":"Rigid Stocks",
        "Skill":"(Weapon) B/R",
        "InstallTime":"36 Hours",
        "InstallTN":4,
        "Mount":"None",
        "Tools":"Kit",
        "Weight":.5,
        "FCU":0,
        "DP":40,
        "RC":1,
        "Concealability":-1
    },
    "Folding Stock":{
        "Name":"Folding Stock",
        "Skill":"(Weapon) B/R",
        "InstallTime":"36 Hours",
        "InstallTN":4,
        "Mount":"None",
        "Tools":"Kit",
        "Weight":.5,
        "FCU":0,
        "DP":40,
        "RC":1
    },
    "Shock Pads":{
        "Name":"Folding Stock",
        "Skill":"(Weapon) B/R",
        "InstallTime":"2 Hours",
        "InstallTN":3,
        "Mount":"None",
        "Tools":"Kit",
        "Weight":2.5,
        "FCU":0,
        "DP":40,
        "RC":1
    },
    "Hip Pads":{
        "Name":"Folding Stock",
        "Skill":"(Weapon) B/R",
        "InstallTime":"2 Hours",
        "InstallTN":3,
        "Mount":"None",
        "Tools":"Kit",
        "Weight":2,
        "FCU":0,
        "DP":40,
        "RC":1
    },
    "Sawed-Off Shotgun Barrel (Kit Installed)":{
        "Name":"Sawed-Off Shotgun Barrel (Kit Installed)",
        "Skill":"Shotguns B/R",
        "InstallTime":"2 Hours",
        "InstallTN":3,
        "Mount":"Barrel",
        "Tools":"Kit",
        "Weight":-1,
        "FCU":0,
        "DP":8,
        "Concealability":2,
        "Extra":"+1 TN on all shots"
    },
    "Sawed-Off Shotgun Barrel (Shop Installed)":{
        "Name":"Sawed-Off Shotgun Barrel (Shop Installed)",
        "Skill":"Shotguns B/R",
        "InstallTime":"2 Hours",
        "InstallTN":3,
        "Mount":"Barrel",
        "Tools":"Shop",
        "Weight":-1,
        "FCU":0,
        "DP":8,
        "Concealability":2
    },
    "Imaging Systems (Flashlight)":{
        "Name":"Imaging Systems (Flashlight)",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"Top,Under",
        "Tools":"Kit",
        "Weight":.25,
        "FCU":-.25,
        "DP":25,
    },
    "Imaging Systems (Gun Cam)":{
        "Name":"Imaging Systems (Gun Cam)",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"Top,Under",
        "Tools":"Kit",
        "Weight":.25,
        "FCU":-.25,
        "DP":400,
    },
    "Imaging Systems (Low-light)":{
        "Name":"Imaging Systems (Low-light)",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"Top,Under",
        "Tools":"Kit",
        "Weight":.25,
        "FCU":-.25,
        "DP":300,
    },
    "Imaging Systems (Magnification 1)":{
        "Name":"Imaging Systems (Magnification 1)",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"Top,Under",
        "Tools":"Kit",
        "Weight":.25,
        "FCU":-.25,
        "DP":100
    },
    "Imaging Systems (Magnification 2)":{
        "Name":"Imaging Systems (Magnification 2)",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"Top,Under",
        "Tools":"Kit",
        "Weight":.25,
        "FCU":-.25,
        "DP":160
    },
    "Imaging Systems (Magnification 3)":{
        "Name":"Imaging Systems (Magnification 3)",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"Top,Under",
        "Tools":"Kit",
        "Weight":.25,
        "FCU":-.25,
        "DP":240
    },
    "Imaging Systems (Thermographic)":{
        "Name":"Imaging Systems (Thermographic)",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"Top,Under",
        "Tools":"Kit",
        "Weight":.25,
        "FCU":-.25,
        "DP":300
    },
    "Underbarrel Weapon (Bayonet)":{
        "Name":"Underbarrel Weapon (Bayonet)",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"Under",
        "Tools":"Kit",
        "Weight":.75,
        "FCU":-.25,
        "DP":10
    },
    "Underbarrel Weapon (Gapple Gun)":{
        "Name":"Underbarrel Weapon (Gapple Gun)",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"Under",
        "Tools":"Kit",
        "Weight":2,
        "FCU":-.25,
        "DP":100
    },
    "Underbarrel Weapon (Grenade Launcher)":{
        "Name":"Underbarrel Weapon (Grenade Launcher)",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"Under",
        "Tools":"Kit",
        "Weight":2,
        "FCU":-.25,
        "DP":360
    },
    "Underbarrel Weapon (Flamethrower)":{
        "Name":"Underbarrel Weapon (Flamethrower)",
        "Skill":"(Weapon) B/R",
        "InstallTime":"24 Hours",
        "InstallTN":4,
        "Mount":"Under",
        "Tools":"Kit",
        "Weight":0,
        "FCU":-.25,
        "DP":240
    }
}
export default Modifications;